---
services:
 zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8088:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/ttyUSB0
