version: "3.9"

services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassi
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./ha_config:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    restart: unless-stopped

